/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "nonna.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nonna_proto_MotorCmd, nonna_proto_MotorCmd, AUTO)


PB_BIND(nonna_proto_SensorData, nonna_proto_SensorData, AUTO)


PB_BIND(nonna_proto_EnableCmd, nonna_proto_EnableCmd, AUTO)


PB_BIND(nonna_proto_DisableCmd, nonna_proto_DisableCmd, AUTO)


PB_BIND(nonna_proto_NonnaMsg, nonna_proto_NonnaMsg, AUTO)



